### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hgducharme** [hgducharme/meatball#46]
### Move Generation

- [ ] Move flag for checks
- [ ] Move flag for double checks
- [ ] Move flag for discovered checks
- [ ] Move flag for checkmates
- [ ] Implement pawn promotion
- [ ] Implement setting chessboard position from FEN
